### ISSUE TITLE
System.Console.CmdArgs.Implicit, unexpected flag (end): Text

### ISSUE THREAD

**Issue by yongqli** [ndmitchell/cmdargs#19]
Everything works on OSX, but when I compile my program on Linux, I get:

    % ./dist/build/progname/progname
    progname: System.Console.CmdArgs.Implicit, unexpected flag (end): Text

What could be the cause?

**Comment by ndmitchell** [comment]
Hmm, weird. Can you give me a small example that fails? I'm on Windows, which might give us another viewpoint. Are you using the same version of GHC and cmdargs in both cases?

**Comment by j-e-k** [comment]
Here is a simple test case, both machines have identical package versions and are using GHC 7.8.3.

## Main.hs

```{-# LANGUAGE DeriveDataTypeable, OverloadedStrings #-}
module Sample where
import System.Console.CmdArgs
import Data.Text

data Sample = Sample {hello :: Text}
              deriving (Show, Data, Typeable)

sample = Sample{hello = ""}

main = print =<< cmdArgs sample
```

## On OSX:

```
runhaskell Main.hs
Sample {hello = ""}
```

## On Ubuntu 14.10:

```
runhaskell Main.hs 
Main.hs: System.Console.CmdArgs.Implicit, unexpected flag (hello): Text
```

**Comment by j-e-k** [comment]
Replacing `Text` with `String` is one workaround. The following works on both Ubuntu and OSX:

```{-# LANGUAGE DeriveDataTypeable, OverloadedStrings #-}
module Sample where
import System.Console.CmdArgs
import Data.Text

data Sample = Sample {hello :: String}
              deriving (Show, Data, Typeable)

sample = Sample{hello = ""}

main = print =<< cmdArgs sample



```
```
runhaskell Main.hs
Sample {hello = ""}
```

It would be greatly preferred, of course, to not have to use such a workaround though....

**Comment by yongqli** [comment]
On Ubuntu 14.04.1 with `ghc 7.6.3`, `runhaskell Main.hs` works, but on Ubuntu 14.10 with `ghc 7.8.3` it does not.

**Comment by j-e-k** [comment]
This seems like a Cabal Sandbox issue. On  both the `Ubuntu 14.04.1` with `ghc 7.6.3` and `Ubuntu 14.10` with `ghc 7.8.3` [this sample project fails](https://gist.github.com/j-e-k/3a64faf2a4a5fa62e92e), with `cabal run` yielding the error and `runhaskell` working just fine. See `test.sh` to reproduce.

**Comment by yongqli** [comment]
This is cabal's fault.

**Comment by ndmitchell** [comment]
OK, thanks for figuring this out, I'll bear it in mind if people get similar bugs in future.

**Comment by grayjay** [comment]
I reproduced the error with GHC 7.8.4, `cmdargs-0.10.14`, and `text-1.1.0.0` when looking into the cabal issue.

**Comment by ndmitchell** [comment]
@grayjay - do you still believe this is a Cabal error?

**Comment by grayjay** [comment]
I don't think so.  I got the same error with cabal and runhaskell.  It seemed to depend on the version of `text`.

**Comment by ndmitchell** [comment]
Does it go away with the latest version of text?

**Comment by grayjay** [comment]
Yes, there was no error with `text-1.2.2.1`.

**Comment by MichelBoucey** [comment]
@ndmitchell - I'm facing a quite same issue that I never had before on my [ip6addr](https://github.com/MichelBoucey/ip6addr) package which use cmdargs. It compiles but runs with the below error:

.stack-work/install/x86_64-linux/**lts-5.12/7.10.3**/bin/ip6addr 
ip6addr: System.Console.CmdArgs.Implicit, unexpected mode: FlagType " [canonical|pure|full|arpa|unc|random]"

GHC 8 is much more explicit:

.stack-work/install/x86_64-linux/**lts-7.3/8.0.1**/bin/ip6addr 
ip6addr: System.Console.CmdArgs.Implicit, unexpected mode: FlagType " [canonical|pure|full|arpa|unc|random]"
CallStack (from HasCallStack):
  error, called at ./System/Console/CmdArgs/Implicit/Local.hs:106:11 in cmdargs-0.10.14-8WOlFWoK1XlCebTZE2edgd:System.Console.CmdArgs.Implicit.Local
