### ISSUE TITLE
Generate help text if no default mode was specified

### ISSUE THREAD

**Issue by GianlucaGuarini** [ndmitchell/cmdargs#50]
Hi thank you for this awesome helper. 
I am struggling trying to get the help text as default command if no options were specified for example: 
```sh
$ mycli
```
should generate the same output as
```sh
$ mycli --help
```
Do you have any hint to lead me to a possible solution?
Thank you

**Comment by GianlucaGuarini** [comment]
never mind i have found a simple solution:
```hs
import System.Console.CmdArgs (cmdArgsRun)
import System.Console.CmdArgs.Explicit(helpText, HelpFormat(..))

main :: IO()
main = do
  args <- getArgs
  if null args then exitWithHelp
  else parse =<< cmdArgsRun mode

exitWithHelp :: IO a
exitWithHelp = do
  putStr $ show $ helpText [] HelpFormatAll mode
  exitSuccess
```

**Comment by Synthetica9** [comment]
Would be really nice if this were somewhere in the library itself... Any chance of that?
